#
# Module manifest for module 'Add-AzFirewallRule'
#
# Generated by: TTO
#
# Generated on: 7/12/2019
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'Add-AzFirewallRule'

    # Version number of this module.
    ModuleVersion = '0.0.6'

    # Supported PSEditions
    CompatiblePSEditions = @('Core', 'Desktop')

    # ID used to uniquely identify this module
    GUID = 'e1826c6e-c420-4eef-9ac8-185e3669ca6a'

    # Author of this module
    Author = 'Thomas Totter'

    # Company or vendor of this module
    CompanyName = 'Braincourt GmbH - Part of Capgemini'

    # Copyright statement for this module
    Copyright = '(c) Thomas Totter. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'Add-or-update firewall rules for your current client ip address to all Azure Synapse Workspaces & SQL Servers in a provided Resourcegroup.'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Required modules
    RequiredModules = @(
        @{ModuleName = 'Az.Accounts'; ModuleVersion = '2.10.2'; }
        @{ModuleName = 'Az.Synapse';  ModuleVersion = '2.0.0';  }
        @{ModuleName = 'Az.Sql';      ModuleVersion = '4.0.0';  }
    )

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @('Add-AzFirewallRule')

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = @()

    PrivateData = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @("Azure", "Synapse", "SQL", "Firewall", "Rule")

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/brain246/Add-AzFirewallRule'

            # External dependent modules of this module
            ExternalModuleDependencies = @("Az.Accounts", "Az.Synapse", "Az.Sql")

        } # End of PSData hashtable

    } # End of PrivateData hashtable

} # End of module manifest